import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import { useEffect, useState } from 'react';

export default function Home() {
   const [title, setTitle] = useState('Product Manager');
  const titles = ['Product Manager', 'Product Designer'];

  useEffect(() => {
    const intervalId = setInterval(() => {
      setTitle(prevTitle => 
        prevTitle === titles[0] ? titles[1] : titles[0]
      );
    }, 1000);

        // Clear the interval on component unmount
    return () => clearInterval(intervalId);
  }, []);
  
  return (
    <div>
      <Head>
        <title>Ashutosh | {title} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Main/>
    <About/>
    <Skills/>
    <Projects/>
    <Contact/>
    </div>
  )
}
